version: "3.3"

services:
  db:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  flashcards:
    build: .
    # CMD [“bundle”, “exec”, puma, “-C”, “config/puma.rb”]
    # command: bash -c “bundle exec rails s -p 3000 -b ‘0.0.0.0’”
    volumes:
      - ".:/var/www/flashcards"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db

