version: "3.3"

services:
  db:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=postgres_dev
      - POSTGRES_PASSWORD=postgres_dev

  app:
    build: .
    volumes:
      - '.:/var/www/flashcards'
    ports:
      - "3000:3000"
    depends_on:
      - db